apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.AppName }}-pvc
  namespace: {{ .Values.NameSpace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.DiskSize }}
  storageClassName: {{ .Values.StorageClassName | default "csi-cinder-high-speed" }}